services:
  codex:
    image: ghcr.io/aimsucks/codex:latest
    container_name: codex
    restart: unless-stopped
    environment:
      TZ: America/New_York
      DATABASE_URL: ${DATABASE_URL}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_DISCORD_ID: ${AUTH_DISCORD_ID}
      AUTH_DISCORD_SECRET: ${AUTH_DISCORD_SECRET}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_PORT: ${S3_PORT}
      S3_URL: ${S3_URL}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET}
    networks: [ proxy, internal ]
    labels:
      traefik.enable: true
      traefik.http.routers.codex.rule: Host(`${CODEX_URL}`)
      traefik.http.routers.codex.entrypoints: websecure
      traefik.http.routers.codex.tls: true
      traefik.http.routers.codex.tls.certresolver: letsencrypt
      traefik.http.services.codex.loadbalancer.server.port: 3000
    command: >
      /bin/sh -c "npx prisma migrate deploy && pnpm run start"

networks:
  proxy:
    name: proxy
    external: true
  internal:
    name: internal
    external: true
